### PR TITLE
Use param for retry strategy

### PR DESCRIPTION
**Pull request by Lfulcrum**
Allow users to override pipeline retry strategy, if desired. Should be tested before merging.

As mentioned on https://github.com/sanger-pathogens/nextflow-commons/pull/9

### CODE REVIEW

**Comment by flass** [comment]
LGTM but agreed this should be tested and also should come with updated doc across the board of pipeline docs (or maybe just on https://ssg-confluence.internal.sanger.ac.uk/display/PaMI/General+pipeline+info

**Comment by flass** [comment]
what do we think of this PR @Lfulcrum ? do we think it's useful still? given how many changes we've made to piepplines recently we could just enact something like this without so much testing after all.   
If so, we need to resolve conflicts with current main because I don't think this change intends to remove so much from the config beyond changes on L36 and L121 - correct?  
we would still need to document that in Confluence page for generic pipeline usage + on help message (but see with @SamD28  as his help message generator could be made generic and pulled from here in part (and from assorted-sub-workflows repo for other options linked to subwf's runtime)

**Comment by Lfulcrum** [comment]
@flass Agree, this could be merged following a quick test. You think we should keep the lines unchanged other than L36 and L121? I guess I wasn't sure about these non-scalable exit codes, maybe they should always be ignored regardless of `params.retry_strategy`?

**Comment by flass** [comment]
> @flass Agree, this could be merged following a quick test. You think we should keep the lines unchanged other than L36 and L121? I guess I wasn't sure about these non-scalable exit codes, maybe they should always be ignored regardless of `params.retry_strategy`?

ah OK if you're not sure... but if we know these codes are bound to fail the run, we should not retry them, right?  
I don't know what they mean in practice though - are they emitted by the farm LSF? or reflect more an internal process failure?

**Comment by Lfulcrum** [comment]
@flass I think it's both. As in these are normal Linux signals that are modified by LSF. To translate them you have to subtract 128 from them. E.g. 137 -128 = 9 = `SIGKILL`. But yeah, I guess if the user kills the process we don't want it to restart, we want to assume the user always wants to ignore in this case. Similar for the other codes I guess, although in honesty, I haven't looked up what each of them are, or if I once did I can't remember now 😅

**Comment by Lfulcrum** [comment]
For safety, I will reinstate some of the deleted code 👍

**Comment by flass** [comment]
LGTM!

**Comment by Lfulcrum** [comment]
Ran quick test with `strain_mapper` pipeline, introducing an `exit 1` into the reference indexing script. Seems to work as desired:
```
nextflow run . --manifest_of_reads test_manifest_truncated.csv --reference test_data/inputs/ref/GCF_000011265.1.fna --outdir test_strain_mapper_retry_strategy --retry_strategy retry
```
Retries 3 times then pipeline cannot proceed without an index file (but it finishes "Successfully" because we ignore):
```
executor >  lsf (11)
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[ab/de3580] process > STRAIN_MAPPER:INDEX_REF        [100%] 3 of 3, failed: 3...
[dd/fd699b] process > STRAIN_MAPPER:BOWTIE2 (1)      [100%] 2 of 2 ✔
[9a/4fef93] process > STRAIN_MAPPER:CONVERT_TO_BA... [100%] 2 of 2 ✔
[d5/48f541] process > STRAIN_MAPPER:SAMTOOLS_SORT... [100%] 2 of 2 ✔
[3e/7328a4] process > STRAIN_MAPPER:PICARD_MARKDU... [100%] 2 of 2 ✔
[-        ] process > STRAIN_MAPPER:BCFTOOLS_MPILEUP -
[-        ] process > STRAIN_MAPPER:BCFTOOLS_CALL    -
[-        ] process > STRAIN_MAPPER:BCFTOOLS_FILT... -
[-        ] process > STRAIN_MAPPER:FINAL_VCF        -
[-        ] process > STRAIN_MAPPER:CURATE_CONSENSUS -
[e4/520f65] NOTE: Process `STRAIN_MAPPER:INDEX_REF` terminated with an error exit status (1) -- Execution is retried (1)
[8b/5dbd61] NOTE: Process `STRAIN_MAPPER:INDEX_REF` terminated with an error exit status (1) -- Execution is retried (2)
[ab/de3580] NOTE: Process `STRAIN_MAPPER:INDEX_REF` terminated with an error exit status (1) -- Error is ignored
```

Whereas if we don't specify the strategy:
```
nextflow run . --manifest_of_reads test_manifest_truncated.csv --reference test_data/inputs/ref/GCF_000011265.1.fna --outdir test_strain_mapper_retry_strategy
```
We get the following (pipeline still finishes successfully because we ignore):
```
executor >  lsf (9)
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:IRODS_QUERY... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[-        ] process > IRODS_EXTRACTOR:CRAM_EXTRAC... -
[a8/e471d8] process > STRAIN_MAPPER:INDEX_REF        [100%] 1 of 1, failed: 1 ✔
[74/1c89ba] process > STRAIN_MAPPER:BOWTIE2 (1)      [100%] 2 of 2 ✔
[83/bcd7e2] process > STRAIN_MAPPER:CONVERT_TO_BA... [100%] 2 of 2 ✔
[45/fa4fb2] process > STRAIN_MAPPER:SAMTOOLS_SORT... [100%] 2 of 2 ✔
[21/16edaa] process > STRAIN_MAPPER:PICARD_MARKDU... [100%] 2 of 2 ✔
[-        ] process > STRAIN_MAPPER:BCFTOOLS_MPILEUP -
[-        ] process > STRAIN_MAPPER:BCFTOOLS_CALL    -
[-        ] process > STRAIN_MAPPER:BCFTOOLS_FILT... -
[-        ] process > STRAIN_MAPPER:FINAL_VCF        -
[-        ] process > STRAIN_MAPPER:CURATE_CONSENSUS -
[a8/e471d8] NOTE: Process `STRAIN_MAPPER:INDEX_REF` terminated with an error exit status (1) -- Error is ignored
```

**Comment by Lfulcrum** [comment]
Although, maybe we want the pipeline to `terminate` in a case like above? Perhaps the `params.retry_strategy` default should actually be set to `finish`. Sorry merged before discussing, but can create another PR if we want to go that way.

**Pull request merged**
